services:
  ts3bot:
    image: spookylsm2/ts3-afk-bot:latest
    build: .
    container_name: ts3_afk_bot
    ports:
      - "5000:8080" 
    volumes:
      - ./bot_data:/app/config
    restart: always